version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - nonamedreturns
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by sLog.
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package.
            - pkg: github.com/instana/testify
              desc: It's a fork of github.com/stretchr/testify.
    dupl:
      threshold: 100
    errorlint:
      asserts: false
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    godox:
      keywords:
        - FIXME
    govet:
      enable:
        - nilness
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - importas
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
    staticcheck:
      checks:
        - all
        - '-SA1019'
        - '-ST1003' # waiting for package name will be fixed (underscores)
        - '-QF1008' # not need to fix; we understand how to call nested structs
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - lll
          - mnd
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/deckhouse/dmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
