version: 2

project_name: dmt

builds:
  - binary: dmt
    main: ./cmd/dmt
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{ .Tag }} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    gomips:
      - hardfloat
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - '^build\(deps\): bump .* in /docs \(#\d+\)'
      - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
      - '^build\(deps\): bump .* in /scripts/gen_github_action_config \(#\d+\)'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: deckhouse
    name: dmt

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
