# Пример конфигурации DMT с rule-specific impact настройками

# Глобальные настройки для переопределения уровней конкретных правил
global:
  linters-settings:
    container:
      impact: error  # Общий уровень для всех правил контейнера
      rules-settings:
        security-context:
          impact: warn  # Конкретное правило переводится в warning
        image-digest:
          impact: warn
        read-only-root-filesystem:
          impact: ignored  # Полностью игнорировать это правило
    
    module:
      impact: error
      rules-settings:
        definition-file:
          impact: warn
        oss:
          impact: ignored
    
    openapi:
      impact: warn  # Все правила OpenAPI в warning
      rules-settings:
        crds:
          impact: error  # Но CRDs остаются в error
    
    rbac:
      rules-settings:
        user-authz:
          impact: warn
        wildcards:
          impact: ignored

# Локальные настройки модулей (работают как обычно)
linters-settings:
  container:
    exclude-rules:
      security-context:
        - kind: "Deployment"
          name: "legacy-app"
  
  no-cyrillic:
    impact: error
    exclude-rules:
      files: ["README_RU.md"]
      directories: ["docs/ru/"]
