linters-settings:
  documentation:
    impact: warn
    exclude-rules:
      readme:
        modules: ["bad-readme"]
      cyrillic-in-english:
        files: ["README.md"]
    bilingual:
      disable: true
