/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generate

import (
	"maps"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/deckhouse/dmt/pkg/linters/rbac/rules/rbaccontract"
)

const (
	headerPrefix = "# Generated by dmt (rbac/sync) from rbac.yaml, contract "
	headerSuffix = `. Edit rbac.yaml and run "dmt lint --linter rbac --fix", or remove this line to maintain the file by hand.`
)

// Header is the first line of every generated file. The sync autofix rewrites a file only when it
// starts with a header: a file without one is maintained by hand and is left alone.
func Header() string {
	return headerPrefix + rbaccontract.ContractVersion + headerSuffix
}

// ParseHeader reports whether the content starts with a generator header and, if so, the contract
// version it names. A header of another version means the file was generated under an older (or
// newer) contract.
func ParseHeader(content string) (bool, string) {
	line, _, _ := strings.Cut(content, "\n")
	line = strings.TrimRight(line, " \t\r")

	if !strings.HasPrefix(line, headerPrefix) || !strings.HasSuffix(line, headerSuffix) {
		return false, ""
	}

	return true, strings.TrimSuffix(strings.TrimPrefix(line, headerPrefix), headerSuffix)
}

// Rendered is the text of one generated file.
type Rendered struct {
	Path    string
	Content string
}

// Render writes every file of the model as a Helm template. The output is a pure function of the
// model: the same declaration always renders the same bytes.
func Render(m *Model) []Rendered {
	out := make([]Rendered, 0, len(m.Files))
	for _, f := range m.Files {
		out = append(out, Rendered{Path: f.Path, Content: RenderFile(f)})
	}

	return out
}

// RenderFile renders one file: the header, then each object as its own YAML document, wrapped in
// {{- if <when> }} when the object is conditional.
func RenderFile(f File) string {
	var b strings.Builder

	b.WriteString(Header())
	b.WriteByte('\n')

	// Consecutive objects under the same condition share one {{- if }} block.
	open := ""

	for _, o := range f.Objects {
		if o.When != open {
			if open != "" {
				b.WriteString("{{- end }}\n")
			}

			if o.When != "" {
				b.WriteString("{{- if " + o.When + " }}\n")
			}

			open = o.When
		}

		b.WriteString("---\n")
		renderObject(&b, o)
	}

	if open != "" {
		b.WriteString("{{- end }}\n")
	}

	return b.String()
}

func renderObject(b *strings.Builder, o Object) {
	apiVersion := "rbac.authorization.k8s.io/v1"
	if o.Kind == "ServiceAccount" {
		apiVersion = "v1"
	}

	b.WriteString("apiVersion: " + apiVersion + "\n")
	b.WriteString("kind: " + o.Kind + "\n")
	b.WriteString("metadata:\n")
	b.WriteString("  name: " + yamlScalar(o.Name) + "\n")

	if o.Namespace != "" {
		b.WriteString("  namespace: " + yamlScalar(o.Namespace) + "\n")
	}

	b.WriteString("  " + labelsInclude(o.Labels) + "\n")

	if len(o.Annotations) > 0 {
		b.WriteString("  annotations:\n")

		for _, key := range slices.Sorted(maps.Keys(o.Annotations)) {
			b.WriteString("    " + key + ": " + strconv.Quote(o.Annotations[key]) + "\n")
		}
	}

	switch o.Kind {
	case "ServiceAccount":
		if o.AutomountToken != nil {
			b.WriteString("automountServiceAccountToken: " + strconv.FormatBool(*o.AutomountToken) + "\n")
		}
	case "ClusterRole", "Role":
		renderRules(b, o.Rules)
	case "ClusterRoleBinding", "RoleBinding":
		b.WriteString("roleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: " + o.RoleRefKind + "\n  name: " + yamlScalar(o.RoleRefName) + "\n")
		b.WriteString("subjects:\n")

		for _, s := range o.Subjects {
			switch s.Kind {
			case "ServiceAccount":
				b.WriteString("- kind: ServiceAccount\n  name: " + yamlScalar(s.Name) + "\n  namespace: " + yamlScalar(s.Namespace) + "\n")
			default:
				b.WriteString("- apiGroup: rbac.authorization.k8s.io\n  kind: " + s.Kind + "\n  name: " + yamlScalar(s.Name) + "\n")
			}
		}
	}
}

// labelsInclude renders the helm_lib_module_labels call that adds the module labels (heritage,
// module) and the labels the generator sets, keys sorted.
func labelsInclude(labels map[string]string) string {
	if len(labels) == 0 {
		return `{{- include "helm_lib_module_labels" (list .) | nindent 2 }}`
	}

	pairs := make([]string, 0, len(labels))
	for _, key := range slices.Sorted(maps.Keys(labels)) {
		pairs = append(pairs, strconv.Quote(key)+" "+strconv.Quote(labels[key]))
	}

	return `{{- include "helm_lib_module_labels" (list . (dict ` + strings.Join(pairs, " ") + `)) | nindent 2 }}`
}

func renderRules(b *strings.Builder, rules []Rule) {
	if len(rules) == 0 {
		b.WriteString("rules: []\n")
		return
	}

	b.WriteString("rules:\n")

	for _, r := range rules {
		if r.When != "" {
			b.WriteString("{{- if " + r.When + " }}\n")
		}

		first := true
		item := func(key string, values []string) {
			if len(values) == 0 {
				return
			}

			indent := "  "
			if first {
				indent = "- "
				first = false
			}

			b.WriteString(indent + key + ":\n")

			for _, v := range values {
				b.WriteString("  - " + yamlScalar(v) + "\n")
			}
		}

		if len(r.NonResourceURLs) > 0 {
			item("nonResourceURLs", r.NonResourceURLs)
		} else {
			item("apiGroups", r.APIGroups)
			item("resources", r.Resources)
			item("resourceNames", r.ResourceNames)
		}

		item("verbs", r.Verbs)

		if r.When != "" {
			b.WriteString("{{- end }}\n")
		}
	}
}

// yamlScalar quotes the values YAML would otherwise misread: the empty core API group, the
// wildcard, anything starting with an indicator character, and anything with a ": " or " #" inside.
func yamlScalar(v string) string {
	if plainScalarRe.MatchString(v) && !yaml11Reserved[strings.ToLower(v)] {
		return v
	}

	return strconv.Quote(v)
}

// plainScalarRe is the shape a value may take unquoted: a letter, underscore, slash or star,
// then the characters of a Kubernetes name, URL path, API group or verb list. Anything else -- an
// empty string, a leading indicator, a space or a digit first, a trailing colon -- is quoted.
var plainScalarRe = regexp.MustCompile(`^[A-Za-z_/][A-Za-z0-9._/:*-]*[A-Za-z0-9_/*]$|^[A-Za-z_*]$`)

// yaml11Reserved lists the words Helm's YAML 1.1 reader turns into booleans or null; "no" as a
// resource name would render as false.
var yaml11Reserved = map[string]bool{
	"y": true, "yes": true, "n": true, "no": true, "true": true, "false": true,
	"on": true, "off": true, "null": true, "~": true,
}
