/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package rules

import (
	"bytes"
	"context"
	"os"
	"path/filepath"

	"helm.sh/helm/v3/pkg/ignore"

	"github.com/deckhouse/dmt/pkg"
	"github.com/deckhouse/dmt/pkg/errors"
)

const HelmignoreCoverageRuleName = "helmignore-coverage"

// chartMaterial is the set of package-root entries Helm needs in the chart, so
// .helmignore must NOT exclude them and their being uncovered is not a finding.
var chartMaterial = map[string]bool{
	"templates":   true,
	"charts":      true,
	"monitoring":  true,
	"Chart.yaml":  true,
	"values.yaml": true,

	// Generated by the build and imported straight into the image.
	"images_digests.json": true,
}

// CoverageRule reports package-root entries the bundle image carries that no .helmignore
// pattern excludes — files Helm would therefore pull into the chart.
type CoverageRule struct {
	pkg.RuleMeta

	module    pkg.Module
	errorList *errors.LintRuleErrorsList
}

var _ pkg.Rule = (*CoverageRule)(nil)

func NewHelmignoreCoverageRule(m pkg.Module, errorList *errors.LintRuleErrorsList) *CoverageRule {
	return &CoverageRule{
		RuleMeta:  pkg.RuleMeta{Name: HelmignoreCoverageRuleName},
		module:    m,
		errorList: errorList.WithRule(HelmignoreCoverageRuleName),
	}
}

func (r *CoverageRule) Check(_ context.Context) {
	root := r.module.GetPath()
	if root == "" {
		return
	}

	raw, err := os.ReadFile(filepath.Join(root, helmignoreFile))
	if err != nil {
		// A missing .helmignore leaves nothing to compare the tree against. Its absence
		// is bundle-layout's finding to report, not a second copy of it here.
		if os.IsNotExist(err) {
			return
		}

		r.errorList.WithFilePath(helmignoreFile).
			Errorf("Cannot read .helmignore file: %s", err)

		return
	}

	rules, err := ignore.Parse(bytes.NewReader(raw))
	if err != nil {
		r.errorList.WithFilePath(helmignoreFile).
			Errorf("Cannot parse .helmignore: %s", err)

		return
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		r.errorList.WithFilePath(helmignoreFile).
			Errorf("Cannot read package root: %s", err)

		return
	}

	for _, entry := range entries {
		r.checkEntry(rules, entry)
	}
}

// checkEntry reports one package-root entry that no pattern excludes.
func (r *CoverageRule) checkEntry(rules *ignore.Rules, entry os.DirEntry) {
	name := entry.Name()

	if name == helmignoreFile || chartMaterial[name] {
		return
	}

	info, err := entry.Info()
	if err != nil {
		r.errorList.WithFilePath(name).
			Errorf("Cannot stat '%s': %s", name, err)

		return
	}

	if rules.Ignore(name, info) {
		return
	}

	kind := "File"
	if entry.IsDir() {
		kind = "Directory"
		name += "/"
	}

	r.errorList.WithFilePath(entry.Name()).
		Warnf("%s '%s' is present in the bundle image and is not listed in .helmignore", kind, name)
}
