name: Update Go Coverage in README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: Run tests and generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out

      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Generate coverage badge
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          COLOR="#4c1"
          VALUE=$COVERAGE
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then COLOR="#dfb317"; fi
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then COLOR="#e05d44"; fi
          echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"120\" height=\"20\"><linearGradient id=\"b\" x2=\"0\" y2=\"100%\"><stop offset=\"0\" stop-color=\"#bbb\" stop-opacity=\".1\"/><stop offset=\"1\" stop-opacity=\".1\"/></linearGradient><mask id=\"a\"><rect width=\"120\" height=\"20\" rx=\"3\" fill=\"#fff\"/></mask><g mask=\"url(#a)\"><rect width=\"70\" height=\"20\" fill=\"#555\"/><rect x=\"70\" width=\"50\" height=\"20\" fill=\"$COLOR\"/><rect width=\"120\" height=\"20\" fill=\"url(#b)\"/></g><g fill=\"#fff\" text-anchor=\"middle\" font-family=\"Verdana,Geneva,DejaVu Sans,sans-serif\" font-size=\"11\"><text x=\"35\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">coverage</text><text x=\"35\" y=\"14\">coverage</text><text id=\"percent\" x=\"95\" y=\"15\" fill=\"#010101\" fill-opacity=\".3\">$VALUE%</text><text id=\"percent\" x=\"95\" y=\"14\">$VALUE%</text></g></svg>" > coverage.svg

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update test coverage badge in README [skip ci]'
          branch: coverage-badge
          file_pattern: README.md coverage.svg
          create_branch: true
          push_options: '--force'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update test coverage badge in README [skip ci]'
          branch: coverage-badge
          title: 'chore: update test coverage badge in README [skip ci]'
          body: 'This PR updates the test coverage badge in README.md and coverage.svg'
          base: main
          delete-branch: true

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
