name: Trdl publisher
on:
  push:
    branches:
      - main
    paths:
      - "**/trdl_channels.yaml"
  workflow_dispatch:

jobs:
  publish:
    name: Publish release channels using trdl server
    runs-on: ubuntu-latest
    steps:
      - name: Publish dmt channels
        uses: werf/trdl-vault-actions/publish@main
        with:
          vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
          project-name: dmt
          vault-auth-method: approle
          vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}
